baseurl = "https://kanishk16.github.io/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "github"
    url = "https://github.com/kanishk16"

  [[params.social]]
    name = "email"
    url = "https://kanishkkalra10@gmail.com"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/kanish2k18"

    
[languages]
  [languages.en]
    title = "Kanishk Kalra"
    subtitle = ""
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = '$ echo -e "\a namaskar"'
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "https://kanishk16.github.io/"